FROM ioft/i386-ubuntu:16.04
MAINTAINER Hyeong-Seok Oh <hseok82.oh@samsung.com>

# dependencies for CoreCLR & CoreFX test
RUN apt-get -qqy install \
	gettext \
	libc6-dev \
	libcurl14-openssl-dev \
	libicu-dev curl wget \
	unzip \ 
	libkrb5-dev \
	liblttng-ust-dev \
	libssl-dev \
	libunwind8 \
	libunwind8-dev \
	uuid-dev \
	zlib1g-dev \
	iputils-ping
	
	
	
	
